export const WORLDS = [
  {
    id: 'commons',
    name: 'The Commons',
    glyph: '🌿',
    phase: 'Phase I',
    status: 'live' as const,
    color: '#1D9E75',
    accent: 'rgba(29,158,117,0.1)',
    desc: 'Gathering, ambient presence, and vibes. The social heartbeat of the galaxy.',
    longDesc: 'The Commons is where you simply exist alongside others. No agenda, no performance pressure. Ambient presence lets people feel each other without interrupting. Memory Rooms preserve your group\'s history forever.',
    href: '/commons',
    features: ['Ambient presence auras', 'Memory Rooms', 'Mood-based navigation', 'Contextual tipping'],
  },
  {
    id: 'forge',
    name: 'The Forge',
    glyph: '🔥',
    phase: 'Phase I',
    status: 'live' as const,
    color: '#BA7517',
    accent: 'rgba(186,117,23,0.1)',
    desc: 'Creation — art, music, writing, building. Live performances with real stakes.',
    longDesc: 'The Forge is where things are made. Creators perform live, audiences gather, tips flow in real time. Every creation becomes a permanent artifact in the galaxy\'s history.',
    href: '/forge',
    features: ['Live performance events', 'Contextual tipping', 'Creation ownership', 'Collaborative builds'],
  },
  {
    id: 'arena',
    name: 'The Arena',
    glyph: '⚔️',
    phase: 'Phase II',
    status: 'coming' as const,
    color: '#D85A30',
    accent: 'rgba(216,90,48,0.1)',
    desc: 'Structured debates, faction wars, tournaments. Ideas with consequence.',
    longDesc: 'The Arena is where ideas go to fight. Structured debates with real stakes, faction tournaments, and reputation heists. The crowd shapes the atmosphere.',
    href: '/arena',
    features: ['Structured debates', 'Faction wars', 'Reputation heists', 'Spectator mode'],
  },
  {
    id: 'deep',
    name: 'The Deep',
    glyph: '🔭',
    phase: 'Phase II',
    status: 'coming' as const,
    color: '#378ADD',
    accent: 'rgba(55,138,221,0.1)',
    desc: 'Discovery, philosophy, rabbit holes. Knowledge that ripples across the galaxy.',
    longDesc: 'The Deep rewards curiosity. Discoveries ripple outward as breaking knowledge. The first finder is credited forever. The spatial knowledge graph grows with every revelation.',
    href: '/the-deep',
    features: ['Discovery ripples', 'Spatial knowledge graph', 'First-finder credits', 'Rabbit hole mode'],
  },
  {
    id: 'void',
    name: 'The Void',
    glyph: '🌑',
    phase: 'Phase III',
    status: 'far' as const,
    color: '#7F77DD',
    accent: 'rgba(127,119,221,0.1)',
    desc: 'Procedurally generated mystery. No one knows what\'s there until someone finds it.',
    longDesc: 'The Void generates itself from the galaxy\'s collective consciousness. No one knows what\'s there until someone finds it. Discovery creates permanent monuments.',
    href: '/the-void',

    features: ['Procedural mystery zones', 'Collective consciousness engine', 'Time-limited events', 'Monument creation'],
  },
  {
    id: 'market',
    name: 'The Market',
    glyph: '💱',
    phase: 'Phase III',
    status: 'far' as const,
    color: '#639922',
    accent: 'rgba(99,153,34,0.1)',
    desc: 'Economy, trade, collaborative ownership. Reputation as currency.',
    longDesc: 'The Market is where reputation becomes real. Trade, collaborative ownership, attention markets. Your trust score has value here.',
    href: '/market',
    features: ['Reputation markets', 'Collaborative ownership', 'Attention economy', 'Micro-ownership'],
  },
  {
    id: 'sanctum',
    name: 'The Sanctum',
    glyph: '🪞',
    phase: 'Phase IV',
    status: 'future' as const,
    color: '#a89bff',
    accent: 'rgba(168,155,255,0.1)',
    desc: 'Your inner world. Journaling, reflection, your personal AI oracle.',
    longDesc: 'The Sanctum is yours alone. The AI oracle shows you patterns in your own journey — not to manipulate you, but to help you understand yourself.',
    href: '/sanctum',
    features: ['Private journaling', 'AI oracle (pattern mirror)', 'Emotional arc tracking', 'Personal timeline'],
  },
  {
    id: 'archive',
    name: 'The Archive',
    glyph: '📜',
    phase: 'Phase IV',
    status: 'future' as const,
    color: '#D4537E',
    accent: 'rgba(212,83,126,0.1)',
    desc: 'Galaxy history — legends, lore, living monuments, time capsules.',
    longDesc: 'The Archive is the galaxy\'s living memory. Every major event, creation, and discovery is woven into the lore. Time capsules open years later.',
    href: '/archive',
    features: ['Galaxy lore engine', 'Living monuments', 'Time capsules', 'Cultural artifacts'],
  },
]

export const PERSONAS = [
  { id: 'work', name: 'Work self', world: 'Forge + Arena', color: '#a89bff' },
  { id: 'creative', name: 'Creative self', world: 'Forge + Commons', color: '#d4b896' },
  { id: 'explorer', name: 'Explorer', world: 'Deep + Void', color: '#1D9E75' },
  { id: 'social', name: 'Social self', world: 'Commons', color: '#378ADD' },
  { id: 'competitor', name: 'Competitor', world: 'Arena', color: '#D85A30' },
  { id: 'private', name: 'Private self', world: 'Sanctum only', color: '#444441' },
]

export const PRESENCE_STATES = [
  { id: 'deep-work', label: 'Deep work', color: '#1D9E75', desc: 'Focused, calm glow' },
  { id: 'open', label: 'Open to connect', color: '#a89bff', desc: 'Soft pulse' },
  { id: 'creating', label: 'Creating', color: '#BA7517', desc: 'Warm aura' },
  { id: 'exploring', label: 'Exploring', color: '#378ADD', desc: 'Drifting shimmer' },
  { id: 'competing', label: 'In the Arena', color: '#D85A30', desc: 'Sharp edges' },
  { id: 'resting', label: 'Resting', color: '#444441', desc: 'Dim, quiet' },
]

export const NAV_LINKS = [
  { label: 'Worlds', href: '/worlds' },
  { label: 'Identity', href: '/profile' },
  { label: 'Experience', href: '/#entertainment' },
  { label: 'Manifesto', href: '/#manifesto' },
]
