export const WORLDS = [
  {
    id: 'commons',
    name: 'The Commons',
    glyph: '🌿',
    phase: 'Phase I',
    status: 'live' as const,
    color: '#1D9E75',
    accent: 'rgba(29,158,117,0.1)',
    desc: 'Gathering, ambient presence, signals. The social heartbeat of the galaxy.',
    longDesc: 'The Commons is where you simply exist alongside others. No agenda, no performance pressure. Drop signals, join memory rooms, and feel the pulse of the galaxy in real time.',
    href: '/commons',
    features: ['Ambient presence map', 'Memory Rooms', 'Mood-tagged signals', 'Live reactions'],
  },
  {
    id: 'forge',
    name: 'The Forge',
    glyph: '🔥',
    phase: 'Phase I',
    status: 'live' as const,
    color: '#BA7517',
    accent: 'rgba(186,117,23,0.1)',
    desc: 'Creation — art, music, writing, building. Live transmissions with real stakes.',
    longDesc: 'The Forge is where things are made. Creators transmit live, audiences gather, contextual tips flow in real time. Every creation becomes a permanent artifact.',
    href: '/forge',
    features: ['Live transmissions', 'Contextual tipping', 'Creation artifacts', 'Signal feed'],
  },
  {
    id: 'arena',
    name: 'The Arena',
    glyph: '⚔️',
    phase: 'Phase I',
    status: 'live' as const,
    color: '#D85A30',
    accent: 'rgba(216,90,48,0.1)',
    desc: 'Structured debates, faction wars. Ideas with consequence.',
    longDesc: 'The Arena is where ideas go to fight. Structured debates with real stakes, faction wars, and live voting. The crowd shapes the atmosphere.',
    href: '/arena',
    features: ['Structured debates', 'Live voting', 'Faction wars', 'Debate reputation'],
  },
  {
    id: 'deep',
    name: 'The Deep',
    glyph: '🔭',
    phase: 'Phase I',
    status: 'live' as const,
    color: '#378ADD',
    accent: 'rgba(55,138,221,0.1)',
    desc: 'Discovery, philosophy, knowledge. Ideas that ripple across the galaxy.',
    longDesc: 'The Deep rewards curiosity. Post discoveries that ripple outward. The first finder is credited forever. Knowledge grows with every revelation.',
    href: '/the-deep',
    features: ['Discovery ripples', 'Tag filtering', 'First-finder credits', 'Galaxy-wide notifications'],
  },
  {
    id: 'void',
    name: 'The Void',
    glyph: '🌑',
    phase: 'Phase I',
    status: 'live' as const,
    color: '#7F77DD',
    accent: 'rgba(127,119,221,0.1)',
    desc: 'Procedural mysteries. Be the first to solve and earn a permanent monument.',
    longDesc: 'The Void generates mysteries that expire. Decode clues, submit answers, race others. First solver earns a monument in The Archive and a massive rep boost.',
    href: '/the-void',
    features: ['Weekly mysteries', 'Clue reveal system', 'First-solver monuments', 'Discovery rep boost'],
  },
  {
    id: 'market',
    name: 'The Market',
    glyph: '💱',
    phase: 'Phase II',
    status: 'live' as const,
    color: '#639922',
    accent: 'rgba(99,153,34,0.1)',
    desc: 'Reputation as currency. Trade rep dimensions. See who leads the galaxy.',
    longDesc: 'The Market is where reputation has real value. Trade rep dimensions with others, see the galaxy leaderboard, and watch the economy of trust unfold.',
    href: '/market',
    features: ['Rep leaderboard', 'Rep trading', 'Trade activity feed', '6 dimensions'],
  },
  {
    id: 'sanctum',
    name: 'The Sanctum',
    glyph: '🪞',
    phase: 'Phase II',
    status: 'live' as const,
    color: '#a89bff',
    accent: 'rgba(168,155,255,0.1)',
    desc: 'Your inner world. Private journaling and your personal AI oracle.',
    longDesc: 'The Sanctum is yours alone. The AI oracle reads your signals, discoveries and journal to show you patterns in your own journey — not to manipulate, but to illuminate.',
    href: '/sanctum',
    features: ['Private journaling', 'AI oracle', 'Mood tracking', 'Pattern insights'],
  },
  {
    id: 'archive',
    name: 'The Archive',
    glyph: '📜',
    phase: 'Phase II',
    status: 'live' as const,
    color: '#D4537E',
    accent: 'rgba(212,83,126,0.1)',
    desc: 'Galaxy history — legends, lore, living monuments.',
    longDesc: 'The Archive is the galaxy\'s living memory. Every major event, solved mystery, and discovery is woven into the lore. Legends are real people.',
    href: '/archive',
    features: ['Galaxy lore', 'Living monuments', 'Legends leaderboard', 'Galaxy stats'],
  },
]

export const PERSONAS = [
  { id: 'work',       name: 'Work self',     world: 'Forge + Arena',  color: '#a89bff' },
  { id: 'creative',   name: 'Creative self', world: 'Forge + Commons', color: '#d4b896' },
  { id: 'explorer',   name: 'Explorer',      world: 'Deep + Void',    color: '#1D9E75' },
  { id: 'social',     name: 'Social self',   world: 'Commons',        color: '#378ADD' },
  { id: 'competitor', name: 'Competitor',    world: 'Arena',          color: '#D85A30' },
  { id: 'private',    name: 'Private self',  world: 'Sanctum only',   color: '#444441' },
]

export const PRESENCE_STATES = [
  { id: 'deep-work',  label: 'Deep work',       color: '#1D9E75', desc: 'Focused, calm glow' },
  { id: 'open',       label: 'Open to connect', color: '#a89bff', desc: 'Soft pulse' },
  { id: 'creating',   label: 'Creating',        color: '#BA7517', desc: 'Warm aura' },
  { id: 'exploring',  label: 'Exploring',       color: '#378ADD', desc: 'Drifting shimmer' },
  { id: 'competing',  label: 'In the Arena',    color: '#D85A30', desc: 'Sharp edges' },
  { id: 'resting',    label: 'Resting',         color: '#444441', desc: 'Dim, quiet' },
]
